import { useNavigate } from 'react-router-dom';
import './Legal.css';

export default function Terms() {
  const navigate = useNavigate();

  return (
    <div className="legal-root">
      <header className="legal-topbar">
        <button className="legal-back" onClick={() => window.history.length > 2 ? navigate(-1) : navigate('/')}>← BACK</button>
        <span className="legal-brand">PITCHIT</span>
        <span className="legal-label">LEGAL</span>
      </header>

      <main className="legal-content">
        <p className="legal-eyebrow">TERMS OF SERVICE</p>
        <h1 className="legal-title">Terms & Conditions</h1>
        <p className="legal-updated">Last updated: July 2026</p>

        <section className="legal-section">
          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using PitchIt ("the Project"), you agree to be bound by these Terms of Service. 
            If you do not agree to these terms, do not use the Project. I reserve the right to modify these terms 
            at any time, and your continued use of the Project constitutes acceptance of any changes.
          </p>
        </section>

        <section className="legal-section">
          <h2>2. Description of Project</h2>
          <p>
            PitchIt is an experimental AI-powered presentation training platform created by an individual developer. 
            It provides real-time feedback on your pitch delivery, structure, and persuasiveness using 
            audio and video capture, speech-to-text transcription, and large language model analysis.
          </p>
        </section>

        <section className="legal-section">
          <h2>3. User Responsibilities</h2>
          <p>
            You are responsible for all activity that occurs under your session. You agree not to use the 
            Project for any unlawful purpose or in any way that interrupts, damages, or impairs the service. 
            You must ensure you have the appropriate rights to any content you present or upload.
          </p>
        </section>

        <section className="legal-section">
          <h2>4. AI-Generated Feedback Disclaimer</h2>
          <p>
            Feedback generated by the AI system is provided for educational and training purposes only. 
            It does not constitute professional advice. Scores, ratings, and recommendations are algorithmic 
            assessments and should not be interpreted as definitive evaluations of your professional capabilities.
          </p>
        </section>

        <section className="legal-section">
          <h2>5. Limitation of Liability</h2>
          <p>
            The Project is provided "as is" without warranties of any kind, express or implied. The creator of 
            PitchIt shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising 
            from your use of the Project.
          </p>
        </section>

      </main>

      <footer className="legal-footer">
        <span>© 2026 PITCHIT. A PROJECT BY FILIP ZIGMUND.</span>
      </footer>
    </div>
  );
}
